#### 0. GETTING STARTED IN R

# www.bioconductor.org has instructions how to install R
# and how to install BioC packages

# packages come with Vignettes (manuals)
library(package)
openVignette(package)

# more extensive help per function is available with
?function

# you can even get help on help
?help

# to see what version of R and packages you are working with
sessionInfo()

# to get back previous commands, use the arrow up/arrow down
# to stop a function, press Esc
# to save a picture, go to File >> Save while the picture window is active


# the -> and = are the same when defining an object




#### 1. WORKING DIRECTORY

# set the working directory
setwd() # use forward or double backward slashes to separate directories
# when using the Windows version of R, you can also browse to your working directory
# using the File >> Change dir option

# to ask which is your working directory
getwd()

# the working directory is used to read files from and save files to
# to see the content of your working directory
dir(getwd())
# or simply
dir()




#### 2. IMPORT AND EXPORT OF DATA

# to read a tab-delimited text file into R
data <- read.table("text.txt", sep="\t", header=T)

# this will also read files with empty cells and replace them by NA
data <- read.delim("text.txt", sep="\t", header=T)

# to export a data frame or matrix to a tab-delimited file
write.table(data, row.names=F, sep="\t", quote=F)

# save an R object
save(object, file="object.RData")

# loading the object back into R workspace
load("object.RData")

# saving the workspace plus all objects
save.image("analysis.RData") # can be opened by double-clicking

# reading in a function from a text file
source("your_function.r")

# to save all your commands from one session
savehistory("my.history.RHistory")




#### 3. OBJECTS IN R

# vector of variables
my.vector = 2
my.vector = c(2,4)
my.vector = seq(from=1,to=1000,by=5)
my.vector = c(rep(1,5),rep(0,5))

# matrix, all entries are numeric, can have column names and row names 
my.matrix = matrix(seq(from=1,to=1000,by=5),nrow=10)      
# default is fill one column at a time, otherwise use byrow = TRUE

# array, same as matrix, but may have more than two dimensions
my.array = array(seq(from=1,to=1000,by=5),dim=c(5,4,10))

# data frame, similar to matrix but can have both numeric and character columns

# specialized objects
# in the microarray field, some standard data objects are used
# these contain multiple slots with e.g. expression data,
# information on the subjects, gene annotation, print run, etc.

# examples of specialized objects
# RGList (limma): after reading in red and green channel data
# MAList (limma): after normalization of RGList
# AffyBatch (affy): after reading in the CEL files
# ExpressionSet (biobase): after normalization of AffyBatch
library(Biobase)
help("ExpressionSet-class")




#### 4. EXPLORING R OBJECTS

# objects in R can be of many different formats, or combine different formats into one object
# e.g. a vector (one dimension), matrix or data frame (rows and columns)
# an object generated by e.g. the vsn package consists of different parts: 
# the matrix of normalized data, but also a description of the normalization parameters
# some objects contain phenotype data (sample description) in addition to the expression data, etc.

# to see the objects in your R workspace
ls()

# to ask the class of an object
class(object) # e.g. matrix, data frame, factor, object defined by specific package

# asking the dimensions of objects
dim(object) # if there are rows and columns
length(object) # if there is only one dimension
summary(object)

# to see the names of columns
names(data)      # only works for data frames
colnames(data)   # works for data frames, matrices, tables, etc.

# to view the first few rows/columns
# note that the rows are always first, then the columns
data[1:3,1:10]   # gives rows 1 to 3 and columns 1 to 10
data[1:3, ]      # gives rows 1 to 3 and all columns
data[1:3, c(1:3,5,7:10)]      # gives rows 1 to 3 and columns 1, 2, 3, 5, and 7 to 10
# etc.

# to address a specific column
data[,1]         # gives all rows for the first column

# if the column has a name, e.g. "ID", you can also write
data$ID          # or:
data[,"ID"]      # or:
data["ID"]

# to combine columns (objects should have same number of rows)
cbind(data$ID, data$Log)
cbind(data[,1], data[,2])

# to combine rows
rbind(data[1:10,], data[100:110,])



# see also R and BioC practical with introduction to R exercises
# http://dial.liacs.nl/Courses/CMSB%20Courses.html
# with a lot of information on plotting, saving plots, etc.
